### ISSUE TITLE
Add string representation

### ISSUE THREAD

**Issue by saraedum** [flatsurf/pyeantic#1]
i.e., fix https://github.com/flatsurf/exact-real/issues/34.

**Comment by saraedum** [comment]
@videlec: There's now a string representation for elements but strangely `renf_class` has no `operator<<` yet.

**Comment by videlec** [comment]
The reason is that I did not make my mind about the best string representation to use. Perhaps the default from `this->to_string()` is just fine.

**Comment by videlec** [comment]
At least it is declared at [renfxx.h line 193-195](https://github.com/videlec/e-antic/blob/master/e-antic/renfxx.h#L193-L195).

**Comment by videlec** [comment]
I am not sure what is the best way to represent a number field... maybe simply
```
NumberField(poly, embedding)
```

**Comment by videlec** [comment]
See https://github.com/videlec/e-antic/pull/57

**Comment by videlec** [comment]
Even after https://github.com/videlec/e-antic/pull/57 the string representation is not available
```
>>> from pyeantic import eantic
>>> K = eantic.renf_class('x^2 - 2', 'x', '[1.4142 +/- 0.0001]')
>>> K
<cppyy.gbl.eantic.renf_class object at 0x555a54f156f0>
```
Is that to be expected?

For elements, it works fine :-)
```
>>> eantic.renf_elem_class(K, 'x')
(x ~ 1.414214)
```

**Comment by saraedum** [comment]
That's expected. It needs to be declared here: https://github.com/flatsurf/pyeantic/blob/master/src/pyeantic/pyeantic/cppyy_eantic.py#L86
