### ISSUE TITLE
test file eantic_sage.py ignored in sage environment

### ISSUE THREAD

**Issue by videlec** [flatsurf/pyeantic#15]
I am inside a Sage environment (`sage -sh`) compiled with Python 3. The `make check` only runs `renf.py`, `renf_elem.py`, `doctest.sh`.

[config.log](https://github.com/flatsurf/pyeantic/files/3361373/config.log)

**Comment by saraedum** [comment]
Did you run `./bootstrap` to regenerate the `configure.sh`?

**Comment by videlec** [comment]
I did not. But after I do, nothing changes.

[config.log](https://github.com/flatsurf/pyeantic/files/3363676/config.log)

**Comment by saraedum** [comment]
I'm not sure that's related but the `eantic_sage.py` was not linked correctly in `configure.ac` and also missing from `make dist`. Can you check again now?

**Comment by videlec** [comment]
Now it is ok.
