### ISSUE TITLE
segfault with invalid input

### ISSUE THREAD

**Issue by videlec** [flatsurf/pyeantic#17]
```
>>> from pyeantic import eantic
>>> K = eantic.renf("x^2 - 3", "x", "1.22 +/- 0.1")
ERROR (renf_init): the given polynomial does not define a unique root
```
The error comes from the C part of e-antic (call to `renf_init`).

Should `renf_init` return an error code on failure instead?

**Comment by saraedum** [comment]
Can we maybe wrap things automatically in `sig_on/off()`?

**Comment by saraedum** [comment]
I mean, it's fine IMHO for a C library to crash hard on invalid input. Even for C++ it seems acceptable to me.

**Comment by videlec** [comment]
Sadly, for `sig_on/sig_off` you need to use Cython.

**Comment by saraedum** [comment]
Are you sure about this? I have used other parts from cysignals without Cython before and it worked fine.

**Comment by videlec** [comment]
I am just reading the cysignals README
```
The cysignals package provides mechanisms to handle interrupts (and other signals and errors) in Cython code.
```

**Comment by saraedum** [comment]
Yes, it appears that you cannot just import `macros.h` which defines `sig_on` since it relies on definitions that live in a `.pxd` file.

**Comment by saraedum** [comment]
So something like https://github.com/Plaristote/segvcatch could do the trick.

**Comment by saraedum** [comment]
Let's see what the cppyy author thinks about this: https://bitbucket.org/wlav/cppyy/issues/163/handling-of-c-errors

**Comment by saraedum** [comment]
cppyy can now catch such signals.
