### ISSUE TITLE
Upgrade License

### ISSUE THREAD

**Issue by saraedum** [flatsurf/pyeantic#24]
Currently, we are LGPL 3+. However, we are importing `sage` which is GPL2+. So, it's my understanding that we have to comply with that license and upgrade to GPL3+.

What do you think @videlec?

**Comment by saraedum** [comment]
See https://opensource.stackexchange.com/a/2148 and https://softwareengineering.stackexchange.com/questions/87446/using-a-gplv3-python-module-will-my-entire-project-have-to-be-gplv3-licensed.

**Comment by videlec** [comment]
More precisely, the SageMath distribution is GPLv3 as can be seen [in the doc](http://doc.sagemath.org/html/en/reference/history_and_license/index.html). But all the SageMath source code is GPLv2.

Indeed, LGPL is probably invalid here. Let us switch to GPL2+ or GPL3+ then.
