### ISSUE TITLE
powers not supported

### ISSUE THREAD

**Issue by videlec** [flatsurf/pyeantic#6]
```
>>> from pyeantic import eantic
>>> L = eantic.renf_class("a^2 - 2", "a", "1.41 +/- 0.01")
>>> L.gen() ** 2
Traceback (most recent call last):
...
TypeError: unsupported operand type(s) for ** or pow(): 'renf_elem_class' and 'int'
```

See also https://github.com/videlec/e-antic/issues/58

Is there a special method name in order that cppyy figures that out itself?

**Comment by saraedum** [comment]
Since there's no power operator in C++, I don't think that cppyy does anything automatically here. But we should add that once the C++ interface has powers.

**Comment by videlec** [comment]
Any name suggestion? Is `pow` ok?

**Comment by saraedum** [comment]
Can we specialize `std::pow`? (It's not clear to me whether that's a good idea…)

**Comment by saraedum** [comment]
I am not sure, but we could still do that eventually. Yes, `pow` sounds good to me.

**Comment by saraedum** [comment]
Hm…let's maybe read the standard first: https://en.cppreference.com/w/cpp/language/extending_std

**Comment by saraedum** [comment]
It's not allowed. Clarified in C++20 it seems.

https://stackoverflow.com/questions/8513417/what-can-and-cant-i-specialize-in-the-std-namespace#comment10546152_8513417

So, we could add a function `eantic::pow` just like we have `eantic::floor` and `eantic::ceil`. Additionally `renf_elem_class::pow` does not hurt I think.
